name: aws-blog
on:
  push:
    branches:
      - master              #master 브랜치에 push 되면 밑에 있는 jobs를 실행해라

#jobs의 목적은 jar 파일을 빌드하는 것.
# actions/setup-java@v2는 사용자 정의 배포를 지원하고 Zulu OpenJDK, Eclipse Temurin 및 Adopt OpenJDK를 기본적으로 지원합니다. v1은 Zulu OpenJDK만 지원.
jobs:
  build: # 마음대로 적어도됨.
    runs-on: ubuntu-18.04        #CI 서버를 하나 만들어서 ubuntu설치.
    steps:
      - name: Checkout                  #step1. 첫번째 action(스크립트) - 프로젝트 코드 다운
        uses: actions/checkout@v2
      - name: Set up JDK 11             #step2. 두번째 action(스크립트) - jdk 다운
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew     #step3. gradlew 실행 권한 부여
        run: chmod +x ./gradlew
        shell: bash
      - name: Build with Gradle                        #step4. gradlew 빌드(테스트+jar생성)
        run: ./gradlew clean build
        shell: bash